import Head from 'next/head'
import NavBar from '../Components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>CRUD kimo khan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
